### ISSUE TITLE
要件定義

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/tsunashima-house#1]
* 要件定義といっても、やりたいようにやるので細かくペルソナ立てたりしない。やりたいようにやる。
* 必要最低限の共有事項のみあらかじめアグリーメントを得て進めたい。

---

* 矢萩コメント
```
* ランディングページなイメージ
* 基本的にはフェイスブックとかスペースマーケットへの導線
* フロントページにアイキャッチとFBとかの導線になるようにしといて、あとはオーナー紹介ページ的なページくらい
```

**Comment by Kenta-Yahagi** [comment]
基本的にはまずはMVPで。
作りすぎずに早めにローンチ目指す方向で行きたいっす。

**Comment by kyoyababa** [comment]
前提：
* できるだけコストと時間をかけないことを最優先とする

構成：
* とりあえず１ペラ、スマホ・タブレットファースト。デスクトップはセカンダリ。
    * 縦長になりそうなので、何らかのナビゲーションでUX低下を防ぐ
    * 以下、各セクションの草案
        * メインビジュアル。何か訴求できる美しい写真とロゴ、テキスト等を挿入
            * アイキャッチ的な立ち位置
            * Facebook、スペースマーケットなどのバナー的なもの
        * tagboardの埋め込み
            * いろいろな活用がなされており認知されているというアピールのためのセクション
            * Projecter用に全画面で表示するUIを別に開けるように別途用意しておく
        * コンセプト、運営側からのメッセージ的なセクション
            * 第三者の意見を大量に表示した後に、正式な声明と何らかの画像でのアピールを行う
            * ここで物件名やロゴの説明、設立の経緯なども簡単に紹介できるとよい？
        * スケジュール
            * グーグルカレンダーAPI的な何か？でスケジュールを管理すると思うので、それをJSONで受け取ってUIに反映する

**Comment by Kenta-Yahagi** [comment]
メインでアイキャッチ
→コンセプト、運営側からのメッセージ
→tagboard or スケジュール
て感じに動線流れやすいように設計したい。

問いあわせはとりまなくていいと思う。
WEBは基本的には普段関わりのない人をペルソナとしたときにペルソナが興味をもって、
FBもしくはスペースマーケットの動線的な役割になることと思っているので。

ただ、スケジュールは「興味を引いて、一回きてみる」という流れで必要そうなので、
実装できればよいと思います。このAPI連携なんだけど、サーバサイドの開発いる？
いるならまゆげさんちょっと協力お願いしたい。
あと時間かかりそうなら個人的にはMVPから除外してもいいと思う。

写真ギャラリーはひとまず作って、放置かな。運用大変なので。あったほうがいいけど、「コンセプト、運営側からのメッセージ」の１コンテンツでいいかもね。

会社概要は、とりあえずなしでいいと思う。代わりに運営メンバー紹介でもいいかな。
うーんでも、なくてもいいかも。要議論。

あと基本一軒家で個人住宅なので個人情報はこの部分には載せないという川原さんとの約束あり。

あとは、Google Analyticsだけちょっと仕込みたいかな。とくにサイト閲覧数とフェイスブック、スペースマーケットのコンバージョンだけは最低計測しておいたほうがいいかなと思う。

**Comment by cowhey** [comment]
〉このAPI連携なんだけど、サーバサイドの開発いる？
いるならまゆげさんちょっと協力お願いしたい。
Googleカレンダーをバックエンドにするならクライアント側でいいと思うよ〜。

**Comment by kyoyababa** [comment]
@Kenta-Yahagi @cowhey 
* おそらくGoogle Calendarであればクライアントで受け取るだけで終わるから問題ないはず。
