### ISSUE TITLE
ペーパープロトタイプの設計

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/tsunashima-house#2]

**Comment by Kenta-Yahagi** [comment]
情報共有的な話。
ソーシャルから、もしくはソーシャルへの導線作り的な話だと、tagboard(https://tagboard.com)みたいなサービスいいなーと思ってる。
サイトのアイキャッチにもなるし、プロジェクター使えば部屋のディスプレイにもなるからいいかもなーと思っちょるよ。

確か、1ハッシュタグは無料で使えるので。ちなみに弊社取り扱い製品でふ

**Comment by Kenta-Yahagi** [comment]
[okuruTsunashimaコンセプトダイアグラム.pptx](https://github.com/kyoyababa/tsunashima-house/files/326101/okuruTsunashima.pptx)
サイトの位置付け、UXをコンセプトダイアグラムで整理。

**Comment by Kenta-Yahagi** [comment]
馬場ちゃんパワポ見れる？
ここに書いてあるコンテンツは全て用意する必要はないと思ってるけど、
膨らますならここまでありってとこまで書いてます。

まずはあくまでFacebook、スペースマーケットへの導線。ブログとかretentionに繋がる部分はまずはいらない認識。

**Comment by kyoyababa** [comment]
ありがとう、むしろ最近まったく進められてなくてごめん...

2016-06-22 1:43 GMT+09:00 Yahagi Kenta <notifications@github.com>:

**Comment by kyoyababa** [comment]
ありがとう、むしろ

**Comment by Kenta-Yahagi** [comment]
パワポはやはぎのWEBの構造的なイメージ。
進められるとき無理せず進めてもらえると。
てか本来有料レベルのお願いなのでまじ助かるっす。

**Comment by kyoyababa** [comment]
@Kenta-Yahagi そのパワポとやらはどこだ？？

**Comment by kyoyababa** [comment]
NOTE: 矢萩のPPTをPDFにして再添付
[okuruTsunashima.pdf](https://github.com/kyoyababa/tsunashima-house/files/333451/okuruTsunashima.pdf)

**Comment by kyoyababa** [comment]
![image](https://cloud.githubusercontent.com/assets/12387222/16720340/58d7b200-4770-11e6-8e58-1e8e9c461a15.jpeg)
![image 1](https://cloud.githubusercontent.com/assets/12387222/16720339/58d132c2-4770-11e6-98fb-793e105a5e34.jpeg)
![image 2](https://cloud.githubusercontent.com/assets/12387222/16720341/58d9f6be-4770-11e6-869e-d96905e82bdd.jpeg)
とりあえずなんとなく構想ができたが、時間がないのでできたということにしてこのまま進めてしまう。
