### ISSUE TITLE
デザイン

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/tsunashima-house#3]
* 面倒くさいのでワイヤーフレームは作らず、ペーパープロトタイプから直接PSDに落としていく

**Comment by kyoyababa** [comment]
NOTE: 物件名は `okuru Tsunashima` になった模様

**Comment by kyoyababa** [comment]
NOTE: 時間がほとんどないので、もはやPSDも作らず、設計しながら直接コーディングに落としていってみるか。

**Comment by Kenta-Yahagi** [comment]
物件名は ”okuru”で。TsunashimaつけるとTsunashimaが目立ちすぎるので。

**Comment by kyoyababa** [comment]
NOTE: コーディング開始

**Comment by kyoyababa** [comment]
NOTE: https://github.com/kyoyababa/tsunashima-house/pull/12
