### ISSUE TITLE
フロントエンド環境構築

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/tsunashima-house#4]
## HTML

特にアプリケーション的な要素は必要としないが、コンポーネント化による保守性向上を図りたいので静的なHTMLを吐き出すタスクランナーを設ける。

## CSS

`gulp-sass`, `gulp-autoprefixer`, `gulp-cssmin`, `gulp-inline (if required)`

## JavaScript

* Javaエンジニアでも意味がわかるようにES6 / TypeScriptで書きたいのと、型定義をちゃんとしたい。
* 将来のモジュール化を見据えて、AngularJSまたはReactJSの導入を検討
* とりあえずLP的なものだけでよいのであればjQuery一本も可。

## Build / Deploy

* レンタルサーバーで静的に運用する程度であれば、デプロイはFTPでいいのでは。でもSlackでビルドできると楽しい。でもCoffeeScript書ける人いるかな。

## Others

`if required`

**Comment by Kenta-Yahagi** [comment]
細かい部分は俺の技術力おっついてないわ笑。
馬場ちゃんのやってみたいで基本ＯＫっすよ。
ただ運用面どうするとかの話あるけど(ビルドデプロイとかね)、
ひとまず静的な運用としてとりあえずミニマムな作業感で。

**Comment by kyoyababa** [comment]
@Kenta-Yahagi 終わった。鬼のように堅牢な環境を作ってしまった。笑
